//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriThucOnline_TTN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DAUSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAUSACH()
        {
            this.CT_DONHANG = new HashSet<CT_DONHANG>();
        }
    
        public int MaSach { get; set; }
        [Required(ErrorMessage = "Nhập Tên")]
        public string TenSach { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn NXB")]
        public Nullable<int> MaNXB { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn thể loại")]
        public Nullable<int> MaTL { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn Tác giả")]
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        [Required(ErrorMessage = "Nhập giá tiền")]
        public Nullable<double> GiaTien { get; set; }
        public string PicBook { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số trang")]
        public Nullable<int> SoTrang { get; set; }
        public string BoCucSach { get; set; }
        public string TrichDan { get; set; }
        [Required(ErrorMessage = "Nhập số lượng tồn")]
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> Moi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DONHANG> CT_DONHANG { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        public virtual NXB NXB { get; set; }
    }
}
