//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriThucOnline_TTN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }

        [Required(ErrorMessage = "Vui lòng nhập mã")]
        public string MaKM { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá trị")]
        public Nullable<double> GiaTriKM { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập ngày bắt đầu")]
        public Nullable<System.DateTime> NgayBD { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập ngày kết thúc")]
        public Nullable<System.DateTime> NgayKT { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lần sử dụng")]
        public Nullable<int> SoLanConLai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
